### ISSUE TITLE
Add clippy to CI

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sget-rs#23]

**Comment by Dentrax** [comment]
Here is the example workflow for this task, if someone wants to get to it: https://github.com/Dentrax/kubesql/blob/ce7b41964c8af182e6b0d1e4af80c71466db5b6d/.github/workflows/workflow.yml#L30-L51 👍 

Edit: Oh! Could not see the PR! Sorry.

**Comment by lukehinds** [comment]
> Here is the example workflow for this task, if someone wants to get to it: https://github.com/Dentrax/kubesql/blob/ce7b41964c8af182e6b0d1e4af80c71466db5b6d/.github/workflows/workflow.yml#L30-L51 +1

Yours is much nicer, do you want to push on top of this PR?

We should likely build test to multiple platforms too.
