### ISSUE TITLE
Make passing CI check a requirement for merging PRs

### ISSUE THREAD

**Issue by lkatalin** [sigstore/sget-rs#41]
I think this requires updating branch protection rules for `main`.

Edit: We need to just enable clippy now, which was hanging.

**Comment by imjasonh** [comment]
See #7 at https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

I'm also happy to click through and set this up if you make me a repo admin, or I can walk through it with someone over a video chat if there's any difficulty.

**Comment by lkatalin** [comment]
Thanks @imjasonh ! @jyotsna-penumaka would you be able to see if you have the perms to do this?

**Comment by lkatalin** [comment]
We set the required status checks except we still need to require clippy. We deleted it from requirements because it was hanging. Not sure why.
