### ISSUE TITLE
Race condition on file write

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sget-rs#93]
I am not sure of the root cause yet, but we get the following when coupling outfile with exec

```bash
cargo run -- --outfile /tmp/some.sh --interactive --exec ghcr.io/jyotsna-penumaka/hello_sget:latest
`thread 'main' panicked at 'Execution failed: Os { code: 26, kind: ExecutableFileBusy, message: "Text file busy" }', src/main.rs:95:14`
```

Looks like its from https://github.com/sigstore/sget/pull/88, as when I hard code a script name to replace `path` on the following, it works:

https://github.com/sigstore/sget/blob/decbfd63c391ecefce3eac03bd13e7842a636455/src/utils.rs#L4-L18

**Comment by lukehinds** [comment]
@lmt-swallow might have some ideas.

**Comment by imjasonh** [comment]
I noticed in https://github.com/sigstore/sget/pull/79#issuecomment-1009526165 that before #79 the behavior of exec was subtly broken to always execute `tests/test.sh`, regardless of what outfile was. This seems related?

I'll see if we can get some e2e tests in place that should guard against future regressions like these.

**Comment by lukehinds** [comment]
@imjasonh I think that well may be the case.
